//------------------------------------------------------------------------------ 
// <auto-generated> 
// This code was generated by a tool. 
// 
// Changes to this file may cause incorrect behavior and will be lost if 
// the code is regenerated. 
// </auto-generated> 
//------------------------------------------------------------------------------

using System.ComponentModel.DataAnnotations.Schema;
using System.Data.Entity.ModelConfiguration;

namespace BB.SmsQuiz.Repository.EF.Models.Mapping
{
    public class CompetitionMap : EntityTypeConfiguration<CompetitionData>
    {
        public CompetitionMap()
        {
            // Primary Key
            this.HasKey(t => t.ID);

            // Properties
            this.Property(t => t.CompetitionKey)
                .IsRequired()
                .HasMaxLength(10);

            this.Property(t => t.Question)
                .IsRequired()
                .HasMaxLength(250);

            // Table & Column Mappings
            this.ToTable("Competitions");
            this.Property(t => t.ID).HasColumnName("ID");
            this.Property(t => t.ClosingDate).HasColumnName("ClosingDate");
            this.Property(t => t.CompetitionKey).HasColumnName("CompetitionKey");
            this.Property(t => t.CreatedDate).HasColumnName("CreatedDate");
            this.Property(t => t.Question).HasColumnName("Question");
            this.Property(t => t.Status).HasColumnName("Status");
            this.Property(t => t.CreatedByID).HasColumnName("CreatedByID");

            // Relationships
            this.HasRequired(t => t.User)
                .WithMany(t => t.Competitions)
                .HasForeignKey(d => d.CreatedByID);

        }
    }
}
