//------------------------------------------------------------------------------ 
// <auto-generated> 
// This code was generated by a tool. 
// 
// Changes to this file may cause incorrect behavior and will be lost if 
// the code is regenerated. 
// </auto-generated> 
//------------------------------------------------------------------------------

using System.ComponentModel.DataAnnotations.Schema;
using System.Data.Entity.ModelConfiguration;

namespace BB.SmsQuiz.Repository.EF.Models.Mapping
{
    public class EntrantMap : EntityTypeConfiguration<EntrantData>
    {
        public EntrantMap()
        {
            // Primary Key
            this.HasKey(t => t.ID);

            // Properties
            this.Property(t => t.ContactDetail)
                .IsRequired()
                .HasMaxLength(50);

            // Table & Column Mappings
            this.ToTable("Entrants");
            this.Property(t => t.ID).HasColumnName("ID");
            this.Property(t => t.CompetitionID).HasColumnName("CompetitionID");
            this.Property(t => t.AnswerKey).HasColumnName("AnswerKey");
            this.Property(t => t.Source).HasColumnName("Source");
            this.Property(t => t.ContactType).HasColumnName("ContactType");
            this.Property(t => t.ContactDetail).HasColumnName("ContactDetail");
            this.Property(t => t.EntryDate).HasColumnName("EntryDate");

            // Relationships
            this.HasRequired(t => t.Competition)
                .WithMany(t => t.Entrants)
                .HasForeignKey(d => d.CompetitionID);

        }
    }
}
