//------------------------------------------------------------------------------ 
// <auto-generated> 
// This code was generated by a tool. 
// 
// Changes to this file may cause incorrect behavior and will be lost if 
// the code is regenerated. 
// </auto-generated> 
//------------------------------------------------------------------------------

using System.ComponentModel.DataAnnotations.Schema;
using System.Data.Entity.ModelConfiguration;

namespace BB.SmsQuiz.Repository.EF.Models.Mapping
{
    public class PossibleAnswerMap : EntityTypeConfiguration<PossibleAnswerData>
    {
        public PossibleAnswerMap()
        {
            // Primary Key
            this.HasKey(t => t.ID);

            // Properties
            this.Property(t => t.AnswerText)
                .IsRequired()
                .HasMaxLength(50);

            // Table & Column Mappings
            this.ToTable("PossibleAnswers");
            this.Property(t => t.CompetitionID).HasColumnName("CompetitionID");
            this.Property(t => t.AnswerKey).HasColumnName("AnswerKey");
            this.Property(t => t.AnswerText).HasColumnName("AnswerText");
            this.Property(t => t.IsCorrectAnswer).HasColumnName("IsCorrectAnswer");
            this.Property(t => t.ID).HasColumnName("ID");

            // Relationships
            this.HasRequired(t => t.Competition)
                .WithMany(t => t.PossibleAnswers)
                .HasForeignKey(d => d.CompetitionID);

        }
    }
}
