//------------------------------------------------------------------------------ 
// <auto-generated> 
// This code was generated by a tool. 
// 
// Changes to this file may cause incorrect behavior and will be lost if 
// the code is regenerated. 
// </auto-generated> 
//------------------------------------------------------------------------------

using System;
using System.Data.Entity;
using System.Data.Entity.Infrastructure;
using BB.SmsQuiz.Infrastructure.UnitOfWork;
using BB.SmsQuiz.Repository.EF.Models;
using BB.SmsQuiz.Repository.EF.Models.Mapping;

namespace BB.SmsQuiz.UnitOfWork.EF.Models
{
    public partial class BBSmsQuizDatabaseContext : DbContext, IContext
    {
        static BBSmsQuizDatabaseContext()
        {
            Database.SetInitializer<BBSmsQuizDatabaseContext>(null);
        }

        public BBSmsQuizDatabaseContext()
            : base("Name=BBSmsQuizDatabaseContext")
        {
        }

        public IDbSet<CompetitionData> Competitions { get; set; }
        public IDbSet<EntrantData> Entrants { get; set; }
        public IDbSet<PossibleAnswerData> PossibleAnswers { get; set; }
        public IDbSet<UserData> Users { get; set; }

        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            modelBuilder.Configurations.Add(new CompetitionMap());
            modelBuilder.Configurations.Add(new EntrantMap());
            modelBuilder.Configurations.Add(new PossibleAnswerMap());
            modelBuilder.Configurations.Add(new UserMap());
        }
    }
}
