//------------------------------------------------------------------------------ 
// <auto-generated> 
// This code was generated by a tool. 
// Runtime Version:2.0.50727.42 
// 
// Changes to this file may cause incorrect behavior and will be lost if 
// the code is regenerated. 
// </auto-generated> 
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace BB.SmsQuiz.Repository.EF.Models
{
    public partial class CompetitionData
    {
        public CompetitionData()
        {
            this.Entrants = new List<EntrantData>();
            this.PossibleAnswers = new List<PossibleAnswerData>();
        }

        public System.Guid ID { get; set; }
        public System.DateTime ClosingDate { get; set; }
        public string CompetitionKey { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public string Question { get; set; }
        public byte Status { get; set; }
        public System.Guid CreatedByID { get; set; }
        public virtual UserData User { get; set; }
        public virtual ICollection<EntrantData> Entrants { get; set; }
        public virtual ICollection<PossibleAnswerData> PossibleAnswers { get; set; }
    }
}
