//------------------------------------------------------------------------------ 
// <auto-generated> 
// This code was generated by a tool. 
// Runtime Version:2.0.50727.42 
// 
// Changes to this file may cause incorrect behavior and will be lost if 
// the code is regenerated. 
// </auto-generated> 
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace BB.SmsQuiz.Repository.EF.Models
{
    public partial class PossibleAnswerData
    {
        public System.Guid CompetitionID { get; set; }
        public byte AnswerKey { get; set; }
        public string AnswerText { get; set; }
        public bool IsCorrectAnswer { get; set; }
        public int ID { get; set; }
        public virtual CompetitionData Competition { get; set; }
    }
}
