//------------------------------------------------------------------------------ 
// <auto-generated> 
// This code was generated by a tool. 
// Runtime Version:2.0.50727.42 
// 
// Changes to this file may cause incorrect behavior and will be lost if 
// the code is regenerated. 
// </auto-generated> 
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace BB.SmsQuiz.Repository.EF.Models
{
    public partial class UserData
    {
        public UserData()
        {
            this.Competitions = new List<CompetitionData>();
        }

        public System.Guid ID { get; set; }
        public string Username { get; set; }
        public byte[] Password { get; set; }
        public virtual ICollection<CompetitionData> Competitions { get; set; }
    }
}
